export const KEYEFFECT_STEP = 2;
export const KEYEFFECT_SIDESTEP = 3;
export const KEYEFFECT_ORDERSTEP = 4;
export const KEYEFFECT_JUMP = 5;
export const KEYEFFECT_ORDERCHANGE = 9;
export const KEYEFFECT_CONVERT = 20;

export const BATTLE_FORBIDDEN_KEYEFFECTS = new Set<number>([
  KEYEFFECT_STEP,
  KEYEFFECT_SIDESTEP,
  KEYEFFECT_ORDERSTEP,
  KEYEFFECT_JUMP,
  KEYEFFECT_ORDERCHANGE,
  KEYEFFECT_CONVERT,
]);